int defmazelen = 23;
char *defmazedata[] = {
  "XXXXXXXXXXXXXXXXXXXXXXX",
  "X.X...........8.......X",
  "X.XXX.....X...X9X...X.X",
  "X...X.....X.........6.X",
  "X...X.....X3X.XXX...X.X",
  "X.........X.........7.X",
  "XXX.XXX.X2X...XXX...X.X",
  "X.....X.......X.......X",
  "X.....XXX.X4X.X.XXX...X",
  "X...........X...X.....X",
  "X.XXX.....XXX...X.XXX5X",
  "X.........X.......X...X",
  "X...X...XXX.X1X.X.X...X",
  "X...X.....X.....X.....X",
  "X...XXX.X.X.XXXXX.....X",
  "X.......X.............1",
  "X...X...XXXXX...XXX...X",
  "X...X.....X.....X.....X",
  "X...X.XXX.X.....X.....X",
  "X.......X.......X.....X",
  "XXX...XXXXX...XXXXX...X",
  "X.......X.......X.....X",
  "XXXXXXXXXXXXXXXXXXXXXXX" };
