#!/bin/sh

set -e

pkg=netmaze

if [ "$1" = "configure" ]; then
    if [ -d /usr/doc -a ! -e /usr/doc/$pkg -a -d /usr/share/doc/$pkg ]; then
        ln -sf ../share/doc/$pkg /usr/doc/$pkg
    fi
fi

if [ -x /usr/bin/update-menus ] ; then update-menus ; fi
